[theme]
name = "modern"
#[theme.overrides]
#info_bg = "#076678"
#good_bg = "#79740e"
#warning_bg = "#b57614"
#critical_bg = "#9d0006"
#alternating_tint_bg = "#14100e"

[icons]
name = "awesome"
[icons.overrides]
backlight_empty = "☀️ "
backlight_partial1 = "☀️ "
backlight_partial2 = "☀️ "
backlight_partial3 = "☀️ "
backlight_full = "☀️ "

[[block]]
block = "pacman"

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
device = "DisplayDevice"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "net"
device = "wlan0"
speed_down = true

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB"

[[block]]
block = "cpu"
interval = 1
format = "{barchart}{utilization}%"

[[block]]
block = "time"
interval = 1
format = "%y/%d/%m %a %T"
