blinking-cursor = true
performance = "High"
disable-unfocused-render = false
use-fork = false
use-kitty-keyboard-protocol = false
line-height = 1.0
theme = "OneDark"
padding-x = 10.0
cursor = "▇"
scroll-multiplier = 3.0
env-vars = []
option-as-alt = "false"
ignore-selection-foreground-color = false

[adaptive-theme]
light = "OneLight"
dark = "OneDark"

[navigation]
mode = "BottomTab"
use-current-path = true

[window]
width = 960
height = 480
mode = "Windowed"

[shell]
program = ""
args = ["--login"]

[fonts]
size = 16.0
extras = []

[fonts.regular]
family = "FiraCode Nerd Font Mono"
weight = 400
style = "normal"

[fonts.bold]
family = "FiraCode Nerd Font Mono"
weight = 800
style = "normal"

[fonts.bold-italic]
family = "FiraCode Nerd Font Mono"
weight = 800
style = "italic"

[fonts.italic]
family = "FiraCode Nerd Font Mono"
weight = 400
style = "italic"

[developer]
enable-fps-counter = false
log-level = "OFF"

[bindings]
keys = []
