disable-unfocused-render = false
env-vars = []
ignore-selection-foreground-color = false
line-height = 1.0
option-as-alt = "false"
padding-x = 10.0
performance = "High"
scroll-multiplier = 3.0
theme = "OneDark"
use-fork = false
use-kitty-keyboard-protocol = false

[cursor]
cursor = "▇"
blinking = true

[adaptive-theme]
light = "OneLight"
dark = "OneDark"

[navigation]
mode = "BottomTab"
use-current-path = true

[window]
width = 960
height = 480
mode = "Windowed"

[shell]
program = ""
args = ["--login"]

[fonts]
size = 13.0
extras = []

[fonts.regular]
family = "MonaspiceKr Nerd Font Mono"
weight = 400
style = "normal"

[fonts.bold]
family = "MonaspiceKr Nerd Font Mono"
weight = 800
style = "normal"

[fonts.bold-italic]
family = "MonaspiceKr Nerd Font Mono"
weight = 800
style = "italic"

[fonts.italic]
family = "MonaspiceKr Nerd Font Mono"
weight = 400
style = "italic"

[developer]
enable-fps-counter = false
log-level = "OFF"

[bindings]
keys = []