export GOPATH=$HOME/Projects/golib
export PATH=$GOPATH/bin:$PATH

OS=`uname -s`

if [[ "${OS}" == "Darwin" ]]; then
  alias vi=/Application/MacVim.app/Contents/MacOS/Vim
  alias vim=/Application/MacVim.app/Contents/MacOS/Vim
  export ANDROID_HOME=$HOME/Library/Developer/Xamarin/android-sdk-macosx
elif [[ "${OS}" == "Linux" ]]; then
  export ANDROID_HOME=/opt/android-sdk
  export PATH=$PATH:/opt/vscode:$ANDROID_HOME/tools
fi

