OS=$(uname -s)

export GOPATH=$HOME/Projects/golib

if [[ "${OS}" == "Darwin" ]]; then
  alias vi=/Applications/MacVim.app/Contents/MacOS/Vim
  alias vim=/Applications/MacVim.app/Contents/MacOS/Vim
  export ANDROID_HOME=$HOME/Library/Developer/Xamarin/android-sdk-macosx
  export GOROOT=/usr/local/go
  export PATH=$PATH:$GOROOT/bin:/Library/TeX/texbin
elif [[ "${OS}" == "Linux" ]]; then
  export ANDROID_HOME=/opt/android-sdk
fi

export PATH=$PATH:$ANDROID_HOME/tools:$GOPATH/bin

