[colors]
background       = '#FCFCFC'
black            = '#010101'
blue             = '#4196df'
cursor           = '#fca447'
cyan             = '#51b891'
foreground       = '#5C6166'
green            = '#80ab24'
magenta          = '#9870c3'
red              = '#e7666a'
tabs             = '#9fd32f'
tabs-active      = '#f0cc04'
white            = '#c1c1c1'
yellow           = '#eba54d'

# dim-black        = '#19242f'
# dim-blue         = '#AE7BF8'
# dim-cyan         = '#6fb3ca'
# dim-foreground   = '#dfdfd9'
# dim-green        = '#147c3c'
# dim-magenta      = '#a176cc'
# dim-red          = '#ba3c2a'
# dim-white        = '#EFEFE1'
# dim-yellow       = '#E6A003'

dim-black      = '#343434'
dim-blue       = '#6daee6'
dim-cyan       = '#75c7a8'
dim-foreground = '#FCFCFC'
dim-green      = '#9fd32f'
dim-magenta    = '#b294d2'
dim-red        = '#ee9295'
dim-white      = '#dbdbdb'
dim-yellow     = '#f0bc7b'

light-black      = '#343434'
light-blue       = '#6daee6'
light-cyan       = '#75c7a8'
light-foreground = '#FCFCFC'
light-green      = '#9fd32f'
light-magenta    = '#b294d2'
light-red        = '#ee9295'
light-white      = '#dbdbdb'
light-yellow     = '#f0bc7b'


