[colors]
# Regular colors
background              = '#fcfcfc'
black                   = '#010101'
blue                    = '#4196df'
cursor                  = '#fca447'
cyan                    = '#51b891'
foreground              = '#5c6166'
green                   = '#80ab24'
magenta                 = '#9870c3'
red                     = '#e7666a'
white                   = '#c1c1c1'
yellow                  = '#eba54d'

# UI colors
tabs                    = '#9fd32f'
tabs-foreground         = '#343434'
tabs-active             = '#f0cc04'
tabs-active-highlight   = '#f0bc7b'
tabs-active-foreground  = '#5c6166'
bar                     = '#dbdbdb'
selection-foreground    = '#f0bc7b'
selection-background    = '#bebebe'

# Dim colors
dim-black               = '#343434'
dim-blue                = '#6daee6'
dim-cyan                = '#75c7a8'
dim-foreground          = '#FCFCFC'
dim-green               = '#9fd32f'
dim-magenta             = '#b294d2'
dim-red                 = '#ee9295'
dim-white               = '#dbdbdb'
dim-yellow              = '#f0bc7b'

# Light colors
light-black             = '#343434'
light-blue              = '#6daee6'
light-cyan              = '#75c7a8'
light-foreground        = '#FCFCFC'
light-green             = '#9fd32f'
light-magenta           = '#b294d2'
light-red               = '#ee9295'
light-white             = '#dbdbdb'
light-yellow            = '#f0bc7b'