[colors]
# Regular colors
background              = '#1f2430'
black                   = '#191e2a'
blue                    = '#6dcbfa'
cursor                  = '#ffcc66'
cyan                    = '#90e1c6'
foreground              = '#cbccc6'
green                   = '#a6cc70'
magenta                 = '#cfbafa'
red                     = '#ed8274'
white                   = '#c7c7c7'
yellow                  = '#fad07b'

# UI colors
tabs                    = '#33415e'
tabs-foreground         = '#686868'
tabs-active             = '#ffd580'
tabs-active-highlight   = '#fad07b'
tabs-active-foreground  = '#cbccc6'
bar                     = '#191e2a'
selection-background    = '#33415e'
selection-foreground    = '#cbccc6'

# Dim colors

# Light colors
light-black             = '#686868'
light-blue              = '#73d0ff'
light-cyan              = '#95e6cb'
light-green             = '#bae67e'
light-magenta           = '#d4bfff'
light-red               = '#f28779'
light-white             = '#ffffff'
light-yellow            = '#ffd580'