[colors]
background = '#282c34'
foreground = '#abb2bf'
tabs = '#282c34'
tabs-active = '#61afef'
tabs-active-highlight = '#61afef'
bar = '#282c34'
selection-background = '#5c6370'
selection-foreground = '#e2be7d'
cursor = '#abb2bf'
black = '#282c34'
red = '#e06c75'
green = '#98c379'
yellow = '#e5c07b'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#abb2bf'
light_black = '#000000'
light_red = '#fd5ff1'
light_green = '#94fa36'
light_yellow = '#f5ffa8'
light_blue = '#96cbfe'
light_magenta = '#b9b6fc'
light_cyan = '#85befd'
light_white = '#e0e0e0'