[colors]
background = '#f3f3f3'
foreground = '#2a2c33'
tabs = '#f3f3f3'
tabs-active = '#98c379'
tabs-active-highlight = '#98c379'
bar = '#f3f3f3'
selection-background = '#ededed'
selection-foreground = '#2a2c33'
cursor = '#bbbbbb'
black = '#000000'
red = '#de3e35'
green = '#3f953a'
yellow = '#d2b67c'
blue = '#2f5af3'
magenta = '#950095'
cyan = '#3f953a'
white = '#bbbbbb'
light_black = '#000000'
light_red = '#de3e35'
light_green = '#3f953a'
light_yellow = '#d2b67c'
light_blue = '#2f5af3'
light_magenta = '#a00095'
light_cyan = '#3f953a'
light_white = '#ffffff'