[[ -f ~/.cargo/env ]] && source "$HOME/.cargo/env"
[[ -f /opt/homebrew/bin/brew ]] && eval "$(/opt/homebrew/bin/brew shellenv)"
[[ -f /opt/homebrew/bin/fnm ]] && eval "$(/opt/homebrew/bin/fnm env)"

export PATH="$HOME/.local/bin:$PATH"
