export DOCKER_HOST=$HOME/.colima/docker.sock
export PATH=$HOME/.m2/bin:$HOME/.local/bin:$PATH
export EDITOR=nvim

[[ -f ~/.cargo/env ]] && source "$HOME/.cargo/env"

[[ -f /opt/homebrew/bin/brew ]] && eval "$(/opt/homebrew/bin/brew shellenv)"
[[ -f /opt/homebrew/bin/fnm ]] && eval "$(/opt/homebrew/bin/fnm env)"
