# You can change the names/locations of these if you prefer.
antidote_dir=${ZDOTDIR:-~}/.local/share/antidote
plugins_txt=${ZDOTDIR:-~}/Projects/dotFiles/zsh/zsh_plugins
static_file=${ZDOTDIR:-~}/.zsh_plugins.zsh

zstyle ':antidote:bundle' use-friendly-names 'yes'

# Clone antidote if necessary and generate a static plugin file.
if [[ ! $static_file -nt $plugins_txt ]]; then
  [[ -e $antidote_dir ]] ||
    git clone --depth=1 https://github.com/mattmc3/antidote.git $antidote_dir
  (
    source $antidote_dir/antidote.zsh
    [[ -e $plugins_txt ]] || touch $plugins_txt
    antidote bundle <$plugins_txt >$static_file
  )
fi

# Uncomment this if you want antidote commands like `antidote update` available
# in your interactive shell session:
autoload -Uz $antidote_dir/functions/antidote

if type brew &>/dev/null; then
 FPATH=$(brew --prefix)/share/zsh-completions:$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZVM_INIT_MODE=sourcing

# The plugin will auto execute this zvm_after_init function
function zvm_after_init() {
  # zsh-history-substring-search configuration
  bindkey '^j' history-substring-search-up    # up
  bindkey '^k' history-substring-search-down  # down
}

# zsh theming
GEOMETRY_SEPARATOR=" "
GEOMETRY_TITLE=(geometry_hostname geometry_path)

# source the static plugins file
source $static_file

# cleanup
unset antidote_dir plugins_txt static_file

autoload -Uz compinit && compinit -d "$HOME/.cache/zsh"

HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1

[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"