# Download Znap, if it's not there yet.
[[ -f ~/.local/share/zsh-snap/znap.zsh ]] ||
    git clone --depth 1 -- \
            https://github.com/marlonrichert/zsh-snap.git ~/.local/share/zsh-snap
            
source ~/.local/share/zsh-snap/znap.zsh  # Start Znap

# zsh theming
GEOMETRY_SEPARATOR=" "

# `znap prompt` makes your prompt visible in just 15-40ms!
znap prompt geometry-zsh/geometry

# `znap source` automatically downloads and starts your plugins.
znap source marlonrichert/zsh-autocomplete
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting

# `znap eval` caches and runs any kind of command output for you.
znap eval iterm2 'curl -fsSL https://iterm2.com/shell_integration/zsh'

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export BAT_THEME=ansi

# add some aliases
alias cat="bat"
alias ls="exa -alh"
alias tree="exa -alh -T"
alias du="du -h"
alias df="df -h"
alias free="free -h"
alias nv="nvim"
