# You can change the names/locations of these if you prefer.
antidote_dir=${ZDOTDIR:-~}/.local/share/antidote
plugins_txt=${ZDOTDIR:-~}/Projects/dotFiles/zsh/zsh_plugins
static_file=${ZDOTDIR:-~}/.zsh_plugins.zsh

zstyle ':antidote:bundle' use-friendly-names 'yes'

# Clone antidote if necessary and generate a static plugin file.
if [[ ! $static_file -nt $plugins_txt ]]; then
  [[ -e $antidote_dir ]] ||
    git clone --depth=1 https://github.com/mattmc3/antidote.git $antidote_dir
  (
    source $antidote_dir/antidote.zsh
    [[ -e $plugins_txt ]] || touch $plugins_txt
    antidote bundle <$plugins_txt >$static_file
  )
fi

# Uncomment this if you want antidote commands like `antidote update` available
# in your interactive shell session:
autoload -Uz $antidote_dir/functions/antidote

# zsh theming
GEOMETRY_SEPARATOR=" "

# source the static plugins file
source $static_file

# cleanup
unset antidote_dir plugins_txt static_file

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# bun completions
[ -s "${HOME}/.bun/_bun" ] && source "${HOME}/.bun/_bun"

# Bun
export BUN_INSTALL="/Users/gerlaca1/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export BAT_THEME="TwoDark"

# add some aliases
alias cat="bat"
alias ls="exa -alh"
alias tree="exa -alh -T"
alias du="du -h"
alias df="df -h"
alias free="free -h"
alias nv="nvim"
alias gitui="gitui"

autoload -Uz compinit && compinit